# Generated by Django 5.2.8 on 2025-12-05 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("secundarios", "0006_user_post_resposta_searchlog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resposta",
            name="post",
        ),
        migrations.RemoveField(
            model_name="resposta",
            name="autor",
        ),
        migrations.RemoveField(
            model_name="searchlog",
            name="usuario",
        ),
        migrations.RemoveField(
            model_name="user",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="user",
            name="user_permissions",
        ),
        migrations.DeleteModel(
            name="Post",
        ),
        migrations.DeleteModel(
            name="Resposta",
        ),
        migrations.DeleteModel(
            name="SearchLog",
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
